name: CICD for NodeJs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] //Changed from [14.x to 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build

        env:
          CI: true

  depoly:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} //changed
          username: ${{ secrets.USER }} //changed
          key: ${{ secrets.KEY }} //changed
          port: ${{ secrets.PORT }} //changed
          script: | 
            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
            . ~/.nvm/nvm.sh

             nvm instal 18 //changed from 14 to 18
             npm install -g pm2
             cd ~/CICD
             git pull origin master
             npm install
             npm run build
             pm2 restart api
